In [3]:
from flask import Flask, request
from twilio.twiml.messaging_response import MessagingResponse
from openpyxl import load_workbook, Workbook
import pandas as pd

p2016 = pd.read_excel("nbastats2016.xlsx")
p2017 = pd.read_excel("nbastats2017.xlsx")
p2018 = pd.read_excel("nbastats2018.xlsx")

In [4]:
p2016.head()

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PS/G
0,1,Quincy Acy\acyqu01,PF,25,SAC,59,29,14.8,2.0,3.6,...,0.735,1.1,2.1,3.2,0.5,0.5,0.4,0.5,1.7,5.2
1,2,Jordan Adams\adamsjo01,SG,21,MEM,2,0,7.5,1.0,3.0,...,0.600,0.0,1.0,1.0,1.5,1.5,0.0,1.0,1.0,3.5
2,3,Steven Adams\adamsst01,C,22,OKC,80,80,25.2,3.3,5.3,...,0.582,2.7,3.9,6.7,0.8,0.5,1.1,1.1,2.8,8.0
3,4,Arron Afflalo\afflaar01,SG,30,NYK,71,57,33.4,5.0,11.3,...,0.840,0.3,3.4,3.7,2.0,0.4,0.1,1.2,2.0,12.8
4,5,Alexis Ajinca\ajincal01,C,27,NOP,59,17,14.6,2.5,5.3,...,0.839,1.3,3.3,4.6,0.5,0.3,0.6,0.9,2.3,6.0

In [8]:
p2016['Player']

0                    Quincy Acy\acyqu01
1                Jordan Adams\adamsjo01
2                Steven Adams\adamsst01
3               Arron Afflalo\afflaar01
4               Alexis Ajinca\ajincal01
5                Cole Aldrich\aldrico01
6           LaMarcus Aldridge\aldrila01
7             Cliff Alexander\alexacl01
8                 Lavoy Allen\allenla01
9                  Tony Allen\allento01
10            Al-Farouq Aminu\aminual01
11               Lou Amundson\amundlo01
12             Chris Andersen\anderch01
13             Chris Andersen\anderch01
14             Chris Andersen\anderch01
15              Alan Anderson\anderal01
16             James Anderson\anderja01
17            Justin Anderson\anderju01
18              Kyle Anderson\anderky01
19              Ryan Anderson\anderry01
20      Giannis Antetokounmpo\antetgi01
21     Thanasis Antetokounmpo\antetth01
22            Carmelo Anthony\anthoca01
23               Joel Anthony\anthojo01
24              Keith Appling\applike01
25               Trevor Ariza\arizatr01
26             Darrell Arthur\arthuda01
27                   Omer Asik\asikom01
28              D.J. Augustin\augusdj01
29              D.J. Augustin\augusdj01
                     ...
548             Briante Weber\weberbr01
549               Sonny Weems\weemsso01
550               Sonny Weems\weemsso01
551               Sonny Weems\weemsso01
552                 David West\westda01
553         Russell Westbrook\westbru01
554          Hassan Whiteside\whiteha01
555        Shayne Whittington\whittsh01
556            Andrew Wiggins\wiggian01
557               C.J. Wilcox\wilcocj01
558             Alan Williams\willial03
559            Deron Williams\willide01
560          Derrick Williams\willide02
561           Elliot Williams\williel01
562              Lou Williams\willilo02
563           Marvin Williams\willima02
564               Mo Williams\willima01
565           Justise Winslow\winslju01
566               Jeff Withey\witheje01
567             Christian Wood\woodch01
568         Metta World Peace\artesro01
569            Brandan Wright\wrighbr03
570              Delon Wright\wrighde01
571               Tony Wroten\wroteto01
572               James Young\youngja01
573                 Joe Young\youngjo01
574                Nick Young\youngni01
575            Thaddeus Young\youngth01
576               Cody Zeller\zelleco01
577              Tyler Zeller\zellety01
Name: Player, dtype: object

In [43]:
pattern = '\\\[a-zA-Z0-9_]*'
p2016['Player'] = p2016['Player'].str.replace(pattern, '')
p2016['Player'] = p2016['Player'].str.lower()

In [70]:
players = pd.DataFrame(columns = p2016.columns)
player = 'John Wall'.lower()
year = '2016'

yeardict = {'2016': p2016, '2017': p2017, '2018': p2018}

season = yeardict[year]

mask = season['Player'].str.match(player)

In [71]:
season[mask]
players = players.append(season[mask])

In [72]:
season[mask].loc[:,'Player':'Tm']

        Player Pos  Age   Tm
543  john wall  PG   25  WAS

In [73]:
player = 'Lebron James'.lower()
year = '2016'
season = yeardict[year]
mask = season['Player'].str.match(player)

players = players.append(season[mask])

In [74]:
statistics ='MP'

players
#playerstats = players.loc[:, 'Player':statistics]

#highestplayer = playerstats.loc[playerstats[statistics].idxmax()]

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PS/G
543,446.0,john wall,PG,25.0,WAS,77.0,77.0,36.2,7.4,17.5,...,0.791,0.5,4.4,4.9,10.2,1.9,0.8,4.1,2.1,19.9
264,221.0,lebron james,SF,31.0,CLE,76.0,76.0,35.6,9.7,18.6,...,0.731,1.5,6.0,7.4,6.8,1.4,0.6,3.3,1.9,25.3